index:
    path: /
    controller: App\Controller\UserController::show

user_list:
    path:     /users
    controller: App\Controller\UserController::show

user_create:
    path:     /create
    controller: App\Controller\UserController::create

user_edit:
    path:     /edit/{id}
    controller: App\Controller\UserController::edit

user_info:
    path:     /info/{id}
    controller: App\Controller\UserController::info

user_delete:
    path:     /delete/{id}
    controller: App\Controller\UserController::delete

generate_csv:
    path:     /generateCsv
    controller: App\Controller\CsvController::generateCsv

import_csv:
    path:    /importCsv
    controller: App\Controller\CsvController::importCsv
